from __future__ import annotations

# Shared by the Alembic data migration and tests so the seed data lives in one place.
DOWNLOAD_PROFILES_SEED = [
    {
        "name": "audio",
        "maximumResolution": None,
        "audioOnly": True,
        "preferredContainer": "m4a",
        "preferredVideoCodec": None,
        "preferredAudioCodec": "aac",
        "enabled": True,
        "videoBitrateKbps": None,
        "audioBitrateKbps": None,
        "maxFps": None,
        "pixelFormat": None,
    },
    # Disabled, kept for history so old items' selectedQuality still reads
    # sensibly - no longer offered as a fresh choice.
    {
        "name": "360p",
        "maximumResolution": 360,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": "h264",
        "preferredAudioCodec": "aac",
        "enabled": False,
        "videoBitrateKbps": None,
        "audioBitrateKbps": None,
        "maxFps": None,
        "pixelFormat": None,
    },
    {
        "name": "best",
        "maximumResolution": None,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": "h264",
        "preferredAudioCodec": "aac",
        "enabled": False,
        "videoBitrateKbps": None,
        "audioBitrateKbps": None,
        "maxFps": None,
        "pixelFormat": None,
    },
    {
        "name": "480p",
        "maximumResolution": 480,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": "h264",
        "preferredAudioCodec": "aac",
        "enabled": True,
        "videoBitrateKbps": 160,
        "audioBitrateKbps": 48,
        "maxFps": 24,
        "pixelFormat": "yuv420p",
    },
    {
        "name": "720p",
        "maximumResolution": 720,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": "h264",
        "preferredAudioCodec": "aac",
        "enabled": True,
        "videoBitrateKbps": 850,
        "audioBitrateKbps": 80,
        "maxFps": 30,
        "pixelFormat": "yuv420p",
    },
    {
        "name": "1080p",
        "maximumResolution": 1080,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": "h264",
        "preferredAudioCodec": "aac",
        "enabled": True,
        "videoBitrateKbps": 2100,
        "audioBitrateKbps": 96,
        "maxFps": 30,
        "pixelFormat": "yuv420p",
    },
    # "Original": best available stream up to 1080p, no forced bitrate/codec -
    # only touched by ffmpeg at all if it's genuinely not iPhone-playable.
    {
        "name": "original",
        "maximumResolution": 1080,
        "audioOnly": False,
        "preferredContainer": "mp4",
        "preferredVideoCodec": None,
        "preferredAudioCodec": "aac",
        "enabled": True,
        "videoBitrateKbps": None,
        "audioBitrateKbps": None,
        "maxFps": None,
        "pixelFormat": None,
    },
]
